### ISSUE TITLE
Nostalgie is vulnerable to XSS if SSR data is ever accidentally under visitor or user control

### ISSUE THREAD

**Issue by ggoodman** [ggoodman/nostalgie#19]
As reminded by @Ephem on [a recent podcast episode](https://anchor.fm/frontend-greatness/episodes/Rendering-on-the-Server-epk1mq), an SSR project needs to take care in how it serializes untrusted code into the generated markup. Any user-submitted code could take advantage of some of the surprising nuances of html parsing and attempt to get something like `</script>` injected. After that, game over. Full XSS 😱 .

**Comment by Ephem** [comment]
Nice find and fix! As I mentioned in the episode I've had this vulnerability myself in the past, I'm glad sharing that was helpful. 😄
